name: Publish PPA
on:
  push:
    branches:
      - "master"

jobs:
  launchpad-publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ahoneybun/publish-ppa-package@v1
        with:
          repository: "aaronhoneycutt/Ubuntu-COSMIC"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          series: "noble"
          deb_email: "aaron@system76.com"
          deb_fullname: "Aaron Honeycutt"
